### ISSUE TITLE
Running in shared mode.

### ISSUE THREAD

**Issue by rspider117** [smourier/VCamSample#5]
If you open the vcam in a client app (let's say Zoom) and then try and open it again in a Teams call, we don't get any error, just... blank. 
Reading the docs it seems for single stream media sources, shared mode should be enabled by default.

**Comment by smourier** [comment]
The way each app reports the fact the camera cannot be shared depends on the app. For example Windows' Camera app clearly displays the error.

What documentation are you reffering to? With virtual camera many settings are not available.
