### ISSUE TITLE
Pre-requisites for compilation

### ISSUE THREAD

**Issue by peterpresti** [smourier/VCamSample#7]
I had to install the following to compile under Visual Studio 2022.

Windows Implementation Library.  I installed via NuGet.  It was originally installed, but a re-install fixed some missing header files.

Recent Microsoft Windows SDK or the compiler can't find the virtual camera GUIDs.
https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/

**Comment by smourier** [comment]
WIL latest version is configured in both packages.config files:

https://github.com/smourier/VCamSample/blob/main/VCamSample/packages.config
https://github.com/smourier/VCamSample/blob/main/VCamSampleSource/packages.config

And for recent SDK that don't find guids, I have no problem with the latest SDK, what problem exactly do you have?

**Comment by smourier** [comment]
closed due to inactivity
